"""Initial movies schema

Revision ID: 355fb29ece62
Revises: 79a9cdc1ae02
Create Date: 2026-07-24 18:34:57.597447

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '355fb29ece62'
down_revision: Union[str, Sequence[str], None] = '79a9cdc1ae02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
